CRITICAL - 2023-11-29 21:30:23 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-29 21:30:23 --> Uncaught Error: Class "Locale" not found in D:\xampp\htdocs\proyectoTresBdd\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\xampp\htdocs\proyectoTresBdd\system\Helpers\number_helper.php(55): format_number(14, 2, NULL, Array)
#1 D:\xampp\htdocs\proyectoTresBdd\system\Debug\BaseExceptionHandler.php(145): number_to_size(14, 2)
#2 D:\xampp\htdocs\proyectoTresBdd\app\Views\errors\html\error_exception.php(361): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(14680064)
#3 D:\xampp\htdocs\proyectoTresBdd\system\Debug\BaseExceptionHandler.php(241): include('D:\\xampp\\htdocs...')
#4 D:\xampp\htdocs\proyectoTresBdd\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\xampp\htdocs\proyectoTresBdd\system\Debug\ExceptionHandler.php(112): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\xampp\\htdocs...')
#6 D:\xampp\htdocs\proyectoTresBdd\system\Debug\Exceptions.php(149): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\xampp\htdocs\proyectoTresBdd\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-29 20:32:05 --> Class "App\Models\portadaModel" not found
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-29 20:36:08 --> Class "App\Models\portadaModel" not found
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-29 20:38:43 --> Class "App\Models\portadaModel" not found
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-29 20:38:44 --> Class "App\Models\portadaModel" not found
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-29 20:38:45 --> Class "App\Models\portadaModel" not found
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-29 20:38:45 --> Class "App\Models\portadaModel" not found
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-29 20:38:45 --> Class "App\Models\portadaModel" not found
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-29 20:41:42 --> Class "app\Models\PortadaModel" not found
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-29 20:41:43 --> Class "app\Models\PortadaModel" not found
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-29 20:42:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'root', 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR...', Array, false)
#4 D:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
#6 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#7 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR...', Array, false)
#3 D:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
#5 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#6 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-11-29 20:42:42 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR_TITULO`
FROM `tbl_portada` `a`', [], false)
 3 APPPATH\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-29 20:44:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'root', 'semana7', 3306, '', 0)
#1 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR...', Array, false)
#4 D:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
#6 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#7 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR...', Array, false)
#3 D:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
#5 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#6 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-11-29 20:44:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR_TITULO`
FROM `tbl_portada` `a`', [], false)
 3 APPPATH\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-29 20:44:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', 'root', 'semana7', 3306, '', 0)
#1 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR...', Array, false)
#4 D:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
#6 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#7 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR...', Array, false)
#3 D:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
#5 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#6 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-11-29 20:44:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR_TITULO`
FROM `tbl_portada` `a`', [], false)
 3 APPPATH\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-29 23:39:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'semana7', 3306, '', 0)
#1 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR...', Array, false)
#4 C:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
#6 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#7 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR...', Array, false)
#3 C:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
#5 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#6 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-11-29 23:39:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`POR_TITULO`
FROM `tbl_portada` `a`', [], false)
 3 APPPATH\Models\portadaModel.php(14): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(10): App\Models\portadaModel->tituloModel()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-29 23:48:05 --> Undefined array key "con_contenido"
in APPPATH\Controllers\Home.php on line 20.
 1 APPPATH\Controllers\Home.php(20): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "con_contenido"', 'C:\\xampp\\htdocs\\proyectoTresBdd\\app\\Controllers\\Home.php', 20)
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-29 23:48:31 --> mysqli_sql_exception: Unknown column 'a.con_contedio' in 'field list' in C:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `a`. `te...', 0)
#1 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `a`. `te...')
#2 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `a`. `te...')
#3 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`. `te...', Array, false)
#4 C:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(18): App\Models\portadaModel->contenidoModel()
#6 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#7 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-29 23:48:31 --> Unknown column 'a.con_contedio' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`. `tem_id`, `a`.`con_contedio`
FROM `tbl_contenido` `a`', [], false)
 2 APPPATH\Models\portadaModel.php(28): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Home.php(18): App\Models\portadaModel->contenidoModel()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-29 23:48:32 --> mysqli_sql_exception: Unknown column 'a.con_contedio' in 'field list' in C:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `a`. `te...', 0)
#1 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `a`. `te...')
#2 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `a`. `te...')
#3 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`. `te...', Array, false)
#4 C:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(28): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(18): App\Models\portadaModel->contenidoModel()
#6 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#7 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-29 23:48:32 --> Unknown column 'a.con_contedio' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`. `tem_id`, `a`.`con_contedio`
FROM `tbl_contenido` `a`', [], false)
 2 APPPATH\Models\portadaModel.php(28): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Home.php(18): App\Models\portadaModel->contenidoModel()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-29 23:58:19 --> mysqli_sql_exception: Unknown column 'a.con_id_tema' in 'on clause' in C:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\proyectoTresBdd\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `a`.`con...', 0)
#1 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `a`.`con...')
#2 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `a`.`con...')
#3 C:\xampp\htdocs\proyectoTresBdd\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`con...', Array, false)
#4 C:\xampp\htdocs\proyectoTresBdd\app\Models\portadaModel.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectoTresBdd\app\Controllers\Home.php(18): App\Models\portadaModel->contenidoModel()
#6 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(942): App\Controllers\Home->index()
#7 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\proyectoTresBdd\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectoTresBdd\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-29 23:58:19 --> Unknown column 'a.con_id_tema' in 'on clause'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT `a`.`con_contenido`, `b`.`tem_tema`
FROM `tbl_contenido` `a`
JOIN `tbl_tema` `b` ON `a`.`con_id_tema`=`b`.`tem_id`', [], false)
 2 APPPATH\Models\portadaModel.php(30): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Home.php(18): App\Models\portadaModel->contenidoModel()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
